### ISSUE TITLE
Unit testing with ml-data-hub:2.0.4

### ISSUE THREAD

**Issue by markschiffner** [marklogic-community/ml-unit-test#34]
I am trying to integrate ml-unit-test into ml-data-hub:2.0.4.

1. Test app server not getting created, I followed (https://github.com/marklogic/marklogic-data-hub/issues/1090), but still not working. Tried adding mlTestRestServerName and mlTestDbName - [is issue #26 related ticket?](https://github.com/marklogic-community/ml-unit-test/issues/26)

1. Is there a preferred/convention location to put test modules?  I am placing them under data-hub/test/... 

1. I am guessing that all the appropriate data hub directories get added to mlModulePaths and that I  need to add the test directory as normal.  Are the data hub paths added so that I just have to assign the test directory in the properties file, or do I need to delineate all the data hub paths?

**Comment by rjrudin** [comment]
@markschiffner This is really a Data Hub question, not an ml-unit-test question. There is a Wiki page here that does mention DHF, but that probably ought to be a DHF Wiki page - https://github.com/marklogic-community/ml-unit-test/wiki/Integrating-with-DHF

**Comment by rjrudin** [comment]
Also note that the Wiki page was written against DHF 3.0.0 - I don't know if it'll work for DHF 2.0.4. Again, a DHF matter.

**Comment by markschiffner** [comment]
Thanks, that is where I started. I can push it over to the datahub if that is better

**Comment by rjrudin** [comment]
Please do - this is a matter of getting ml-unit-test to run within the alternate project structure of DHF (which IIRC, doesn't use mlModulePaths).
